# Generated by Django 3.2.7 on 2021-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('education_level', models.CharField(max_length=255)),
                ('referencing_style', models.CharField(max_length=255)),
                ('paper_type', models.CharField(max_length=255)),
                ('paper_length', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('word_count', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('qualification', models.CharField(max_length=256)),
                ('assignment_id', models.CharField(max_length=256)),
                ('star', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('description', models.TextField()),
            ],
        ),
    ]
