# Generated by Django 3.2.6 on 2021-08-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('education_level', models.CharField(max_length=255)),
                ('referencing_style', models.CharField(max_length=255)),
                ('paper_type', models.CharField(max_length=255)),
                ('paper_length', models.CharField(max_length=255)),
                ('question', models.TextField()),
            ],
        ),
    ]
