# Generated by Django 3.2.7 on 2021-11-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_review_assignment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SampleMultipleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sample')),
            ],
        ),
    ]
