# Generated by Django 3.2.7 on 2021-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sample_samplemultiplefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
