# Generated by Django 3.2.7 on 2021-11-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sample_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='samplemultiplefile',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='main.sample'),
        ),
    ]
